name: CI

on:
  push:
    branches:
      - '**'
  workflow_dispatch:
    inputs:
      release:
        description: 'Release'
        required: true
        default: 'true'
      new_version:
        description: 'New version'
        required: true
        default: 'patch'

jobs:
  ci:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: actions/checkout@v2
      - name: Restore Dependency Cache
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-dependency-cache-${{ hashFiles('**/package.json') }}
      - run: npm install
      - run: npm run lint
      - run: npm run build
      - run: npm run test
      - name: Release
        if: ${{ github.event.inputs.release == 'true' }}
        run: |
          npm version ${{ github.event.inputs.new_version }} --git-tag-version=true
          npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
          npm publish
          git push origin && git push origin --tags
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
